### ISSUE TITLE
pip_import can't handle extras in packages that don't have metadata.json

### ISSUE THREAD

**Issue by jdelfino** [bazelbuild/rules_python#95]
I'm hitting an issue that I believe is due to this TODO: https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl.py#L110

Minimal repro here: https://github.com/jdelfino/rules_python_extras_repro

Turns out the googleapis-common-protos wheel only has a METADATA file, but not a metadata.json file, so a rule is not created for the grpc extra in requirements.bzl, which in turn breaks google-cloud-dataflow.

Build output:
```
ERROR: /private/var/tmp/_bazel_jdelfino/657fd0e3b49a2c153d9707a68697c9de/external/pypi__proto_google_cloud_datastore_v1_0_90_4/BUILD:15:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jdelfino/657fd0e3b49a2c153d9707a68697c9de/external/pypi__proto_google_cloud_datastore_v1_0_90_4/BUILD", line 15
		py_library(name = "grpc", deps = [":pkg", req...")])
	File "/private/var/tmp/_bazel_jdelfino/657fd0e3b49a2c153d9707a68697c9de/external/pypi__proto_google_cloud_datastore_v1_0_90_4/BUILD", line 18, in py_library
		requirement("googleapis-common-protos[grpc]")
	File "/private/var/tmp/_bazel_jdelfino/657fd0e3b49a2c153d9707a68697c9de/external/test_deps/requirements.bzl", line 394, in requirement
		fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'googleapis-common-protos[grpc]'
ERROR: 
[snip]
ERROR: Analysis of target '//:import_test' failed; build aborted: Loading failed
INFO: Elapsed time: 11.785s
FAILED: Build did NOT complete successfully (47 packages loaded)
```

**Comment by jdelfino** [comment]
It appears that https://github.com/bazelbuild/rules_python/pull/90 (not reviewed/merged) addresses this issue.

**Comment by evanj** [comment]
This is actually slightly different than the issue addressed by #90 I think: `google-common-protos` does not ship a wheel, it only ships a .tar.gz.: https://pypi.org/project/googleapis-common-protos/#files

I'm not sure what `rules_python` does in this case. (The `rules_pyz` rules we wrote for Bluecore only supports wheels, so to use packages that only ship source code, we end up copying a wheel built by `pip` to a publicly accessible URL, which we can then reference.)

**Comment by jdelfino** [comment]
Somewhere along the line rules_python converts the package to a wheel, and a METADATA file is generated, so #90 does actually fix this - I've tested it and am actively using it form a fork right now. (I originally thought #90 didn't fix the issue, but then realized I needed to regenerate the .par files under tools/)

**Comment by evanj** [comment]
Oh amazing! Although now I'm surprised that the generated wheel does not contain `metadata.json` ... This must be due to a tool version issue of some sort. On my machine, the cached wheel created by pip named `googleapis_common_protos-1.5.3-cp27-none-any.whl` contains `metadata.json`. I suspect this means there is some other issue, where these rules are using a system-provided version of some tool, instead of a specific version referenced from `WORKSPACE`? I'm not sure though, I'm just guessing at this point :)

**Comment by groodt** [comment]
I believe this issue should be closed. `pip_import` was replaced by `pip_install` and  `pip_parse` using fully specified (I.e. “locked”) requirements.txt
